homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 532
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
#  customize_domain: !include customize_domain.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave: !include zwave.yaml

alert: !include alerts.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: False
media_player: !include media_players.yaml
notify: !include notify.yaml
device_tracker: !include device_trackers.yaml
#cover: !include covers.yaml
shell_command: !include shell_commands.yaml
remote: !include remotes.yaml
switch: !include switches.yaml
input_boolean: !include input_booleans.yaml
google_assistant: !include google_assistant.yaml
#google_domains: !include google_domains.yaml
timer: !include timers.yaml

